// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_us_army_lmg_c");
	self attach("head_hero_dunn", "", true);
	self.headModel = "head_hero_dunn";
	self.voice = "american";
}

precache()
{
	precacheModel("body_us_army_lmg_c");
	precacheModel("head_hero_dunn");
}
