// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_us_army_assault_b");
	self attach("head_hero_foley", "", true);
	self.headModel = "head_hero_foley";
	self.voice = "russian";
}

precache()
{
	precacheModel("body_us_army_assault_b");
	precacheModel("head_hero_foley");
}
