// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_rangers_bdu_assault_a_mw3");
	self attach("head_rangers_b_mw3", "", true);
	self.headModel = "head_rangers_b_mw3";
	self.voice = "american";
}

precache()
{
	precacheModel("body_rangers_bdu_assault_a_mw3");
	precacheModel("head_rangers_b_mw3");
}
