// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_us_army_dmg_c_wht");
	self attach("head_army_b_dmg_c_wht", "", true);
	self.headModel = "head_army_b_dmg_c_wht";
	self.voice = "russian";
}

precache()
{
	precacheModel("body_us_army_dmg_c_wht");
	precacheModel("head_army_b_dmg_c_wht");
}
